# Generated by Django 5.1.4 on 2025-01-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
